/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScheduleClass = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'alertMinutesBefore' : IDL.Nat,
  'dayOfWeek' : IDL.Nat,
  'name' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addScheduleClass' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Nat,
      ],
      [ScheduleClass],
      [],
    ),
  'deleteScheduleClass' : IDL.Func([IDL.Nat], [], []),
  'getScheduleClasses' : IDL.Func([], [IDL.Vec(ScheduleClass)], ['query']),
  'updateScheduleClass' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScheduleClass = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'alertMinutesBefore' : IDL.Nat,
    'dayOfWeek' : IDL.Nat,
    'name' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addScheduleClass' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Nat,
        ],
        [ScheduleClass],
        [],
      ),
    'deleteScheduleClass' : IDL.Func([IDL.Nat], [], []),
    'getScheduleClasses' : IDL.Func([], [IDL.Vec(ScheduleClass)], ['query']),
    'updateScheduleClass' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };